### PR TITLE
43: Support both this.db and this.knex

### LINKED ISSUE #43: Save knex instance to this.knex instead of this.db
In order to:
- avoid confusion between having multiple `db`s: `dataSources.db.*` in resolvers and `this.db.*` in data source
- more closely match knex docs (which say eg `knex.select().from('users')`), so we'd do 

`this.knex.select().from('users')` 
instead of 
`this.db.select().from('users')`

https://github.com/cvburgess/SQLDataSource/blob/master/index.js#L17

### PR DESCRIPTION
**Pull request by lorensr**

### CODE REVIEW

**Comment by cvburgess** [comment]
Can you not "deprecate" .db and instead simply add support for .knex?

**Comment by lorensr** [comment]
@cvburgess updated. Lmk if I should change back the README examples as well

**Review by cvburgess — APPROVED** [review]

**Comment by cvburgess** [comment]
thank you for this! Please update the version number in package.json and package-lock.json and I will merge

**Comment by lorensr** [comment]
done, thanks

**Pull request merged**
