### PR TITLE
 Added check for database client in getBatched()

### PR DESCRIPTION
**Pull request by tab00**
In case raw query result transformation to array is needed.

The result of a Knex raw query on a PostgresSQL database does not return an array, so transformation is required.
Other cases may need to be added for other databases.
Transformation is not required if the database is SQLite.

### CODE REVIEW

**Comment by tab00** [comment]
Have you looked at this yet?

**Comment by cvburgess** [comment]
Yes, I have seen this, it just needs some tweaks. Sorry, I have a full-time job, so this is sometimes slower than I would like.

**Comment by cvburgess** [comment]
@tab00 I made some structural changes, linted the codebase, and fixed and listed some other DB clients we are currently not testing.

Do you have any time to look into those other DB configurations? The Knex repo should have mocks so you don't need to actually set those databases up.

**Comment by tab00** [comment]
I'm actually extremely busy too, so don't have time to experiment with other DBs unless in future I eventually need to for my work. I think we can leave further changes to others who have a need for this package to work with the SQL DBs that they are currently using.

**Comment by cvburgess** [comment]
I will attempt to do some light testing.

Will you please open a new issue for your caching problem?

This PR does not have any fixes for that, nor have I confirmed it is even an issue.

**Comment by cvburgess** [comment]
closes #9

**Pull request merged**
