### PR TITLE
v1.4.0 TS Support

### LINKED ISSUE #53: Any plan to support TS?

### PR DESCRIPTION
**Pull request by freshollie**
Extends upon #56 closes #53.

I've taken the liberty to add [tsd](https://github.com/SamVerschueren/tsd) tests too, which ensure that the typescript types match the documentation.

To run `tsd` tests: `yarn test:types` :)

### CODE REVIEW

**Comment by cvburgess** [comment]
This seems perfectly fine to me, thanks for doing the work!
Will try and pull and test ASAP to ensure this works for everyone that uses the lib.
To ensure that the tests are meaningful, I will do the legwork to get CI/CD up and running as well.

**Comment by freshollie** [comment]
Sounds like a good idea! I saw there was no CI or I would have updated it to include this.

**Comment by smacintyre** [comment]
@cvburgess Is it possible to merge this PR? I would like to consider using your library, but this is blocking it. Thank you. I understand you're probably pretty busy.

**Comment by cvburgess** [comment]
@smacintyre adding types is blocking you?

I do plan on merging this but was prioritizing a CI-CD setup first.

**Review by cvburgess — APPROVED** [review]

**Comment by smacintyre** [comment]
@cvburgess  Thank you!

**Pull request merged**
